// <auto-generated />
using System;
using ICTMasterSuite.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ICTMasterSuite.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(IctMasterSuiteDbContext))]
    [Migration("20260408204758_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ICTMasterSuite.Domain.Entities.KnowledgeBaseArticle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Solution")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Symptom")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("TestPhase")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Model", "TestPhase");

                    b.ToTable("KnowledgeBaseArticles", (string)null);
                });

            modelBuilder.Entity("ICTMasterSuite.Domain.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Action")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Module")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Module", "Action")
                        .IsUnique();

                    b.ToTable("Permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000001-0001-0000-0000-000000000000"),
                            Action = 1,
                            CreatedAt = new DateTime(2026, 4, 8, 20, 47, 58, 526, DateTimeKind.Utc).AddTicks(7955),
                            Module = 1,
                            Name = "Authentication.View"
                        },
                        new
                        {
                            Id = new Guid("00000001-0005-0000-0000-000000000000"),
                            Action = 5,
                            CreatedAt = new DateTime(2026, 4, 8, 20, 47, 58, 526, DateTimeKind.Utc).AddTicks(7961),
                            Module = 1,
                            Name = "Authentication.Manage"
                        },
                        new
                        {
                            Id = new Guid("00000002-0001-0000-0000-000000000000"),
                            Action = 1,
                            CreatedAt = new DateTime(2026, 4, 8, 20, 47, 58, 526, DateTimeKind.Utc).AddTicks(7963),
                            Module = 2,
                            Name = "UsersAndProfiles.View"
                        },
                        new
                        {
                            Id = new Guid("00000002-0005-0000-0000-000000000000"),
                            Action = 5,
                            CreatedAt = new DateTime(2026, 4, 8, 20, 47, 58, 526, DateTimeKind.Utc).AddTicks(7965),
                            Module = 2,
                            Name = "UsersAndProfiles.Manage"
                        },
                        new
                        {
                            Id = new Guid("00000003-0001-0000-0000-000000000000"),
                            Action = 1,
                            CreatedAt = new DateTime(2026, 4, 8, 20, 47, 58, 526, DateTimeKind.Utc).AddTicks(7967),
                            Module = 3,
                            Name = "LogFinder.View"
                        },
                        new
                        {
                            Id = new Guid("00000003-0005-0000-0000-000000000000"),
                            Action = 5,
                            CreatedAt = new DateTime(2026, 4, 8, 20, 47, 58, 526, DateTimeKind.Utc).AddTicks(7970),
                            Module = 3,
                            Name = "LogFinder.Manage"
                        },
                        new
                        {
                            Id = new Guid("00000004-0001-0000-0000-000000000000"),
                            Action = 1,
                            CreatedAt = new DateTime(2026, 4, 8, 20, 47, 58, 526, DateTimeKind.Utc).AddTicks(7971),
                            Module = 4,
                            Name = "TriAndAgilentParser.View"
                        },
                        new
                        {
                            Id = new Guid("00000004-0005-0000-0000-000000000000"),
                            Action = 5,
                            CreatedAt = new DateTime(2026, 4, 8, 20, 47, 58, 526, DateTimeKind.Utc).AddTicks(7973),
                            Module = 4,
                            Name = "TriAndAgilentParser.Manage"
                        },
                        new
                        {
                            Id = new Guid("00000005-0001-0000-0000-000000000000"),
                            Action = 1,
                            CreatedAt = new DateTime(2026, 4, 8, 20, 47, 58, 526, DateTimeKind.Utc).AddTicks(7975),
                            Module = 5,
                            Name = "TechnicalHistory.View"
                        },
                        new
                        {
                            Id = new Guid("00000005-0005-0000-0000-000000000000"),
                            Action = 5,
                            CreatedAt = new DateTime(2026, 4, 8, 20, 47, 58, 526, DateTimeKind.Utc).AddTicks(7990),
                            Module = 5,
                            Name = "TechnicalHistory.Manage"
                        },
                        new
                        {
                            Id = new Guid("00000006-0001-0000-0000-000000000000"),
                            Action = 1,
                            CreatedAt = new DateTime(2026, 4, 8, 20, 47, 58, 526, DateTimeKind.Utc).AddTicks(7992),
                            Module = 6,
                            Name = "KnowledgeBase.View"
                        },
                        new
                        {
                            Id = new Guid("00000006-0005-0000-0000-000000000000"),
                            Action = 5,
                            CreatedAt = new DateTime(2026, 4, 8, 20, 47, 58, 526, DateTimeKind.Utc).AddTicks(7993),
                            Module = 6,
                            Name = "KnowledgeBase.Manage"
                        },
                        new
                        {
                            Id = new Guid("00000007-0001-0000-0000-000000000000"),
                            Action = 1,
                            CreatedAt = new DateTime(2026, 4, 8, 20, 47, 58, 526, DateTimeKind.Utc).AddTicks(7995),
                            Module = 7,
                            Name = "SystemSettings.View"
                        },
                        new
                        {
                            Id = new Guid("00000007-0005-0000-0000-000000000000"),
                            Action = 5,
                            CreatedAt = new DateTime(2026, 4, 8, 20, 47, 58, 526, DateTimeKind.Utc).AddTicks(7996),
                            Module = 7,
                            Name = "SystemSettings.Manage"
                        },
                        new
                        {
                            Id = new Guid("00000008-0001-0000-0000-000000000000"),
                            Action = 1,
                            CreatedAt = new DateTime(2026, 4, 8, 20, 47, 58, 526, DateTimeKind.Utc).AddTicks(7997),
                            Module = 8,
                            Name = "Export.View"
                        },
                        new
                        {
                            Id = new Guid("00000008-0005-0000-0000-000000000000"),
                            Action = 5,
                            CreatedAt = new DateTime(2026, 4, 8, 20, 47, 58, 526, DateTimeKind.Utc).AddTicks(7999),
                            Module = 8,
                            Name = "Export.Manage"
                        },
                        new
                        {
                            Id = new Guid("00000009-0001-0000-0000-000000000000"),
                            Action = 1,
                            CreatedAt = new DateTime(2026, 4, 8, 20, 47, 58, 526, DateTimeKind.Utc).AddTicks(8000),
                            Module = 9,
                            Name = "Audit.View"
                        },
                        new
                        {
                            Id = new Guid("00000009-0005-0000-0000-000000000000"),
                            Action = 5,
                            CreatedAt = new DateTime(2026, 4, 8, 20, 47, 58, 526, DateTimeKind.Utc).AddTicks(8002),
                            Module = 9,
                            Name = "Audit.Manage"
                        },
                        new
                        {
                            Id = new Guid("0000000a-0001-0000-0000-000000000000"),
                            Action = 1,
                            CreatedAt = new DateTime(2026, 4, 8, 20, 47, 58, 526, DateTimeKind.Utc).AddTicks(8004),
                            Module = 10,
                            Name = "OfflineSync.View"
                        },
                        new
                        {
                            Id = new Guid("0000000a-0005-0000-0000-000000000000"),
                            Action = 5,
                            CreatedAt = new DateTime(2026, 4, 8, 20, 47, 58, 526, DateTimeKind.Utc).AddTicks(8005),
                            Module = 10,
                            Name = "OfflineSync.Manage"
                        });
                });

            modelBuilder.Entity("ICTMasterSuite.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("dfb4b5b2-4461-44a6-bcc5-6a2ea5a86f55"),
                            CreatedAt = new DateTime(2026, 4, 8, 20, 47, 58, 526, DateTimeKind.Utc).AddTicks(8141),
                            Description = "Acesso total ao sistema",
                            Name = "Administrador"
                        },
                        new
                        {
                            Id = new Guid("2ba5ccdf-6f97-4e5d-9abe-c2dcd4c66355"),
                            CreatedAt = new DateTime(2026, 4, 8, 20, 47, 58, 526, DateTimeKind.Utc).AddTicks(8142),
                            Description = "Acesso operacional tecnico",
                            Name = "Tecnico"
                        });
                });

            modelBuilder.Entity("ICTMasterSuite.Domain.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("dfb4b5b2-4461-44a6-bcc5-6a2ea5a86f55"),
                            PermissionId = new Guid("00000001-0001-0000-0000-000000000000")
                        },
                        new
                        {
                            RoleId = new Guid("2ba5ccdf-6f97-4e5d-9abe-c2dcd4c66355"),
                            PermissionId = new Guid("00000001-0001-0000-0000-000000000000")
                        },
                        new
                        {
                            RoleId = new Guid("dfb4b5b2-4461-44a6-bcc5-6a2ea5a86f55"),
                            PermissionId = new Guid("00000001-0005-0000-0000-000000000000")
                        },
                        new
                        {
                            RoleId = new Guid("dfb4b5b2-4461-44a6-bcc5-6a2ea5a86f55"),
                            PermissionId = new Guid("00000002-0001-0000-0000-000000000000")
                        },
                        new
                        {
                            RoleId = new Guid("2ba5ccdf-6f97-4e5d-9abe-c2dcd4c66355"),
                            PermissionId = new Guid("00000002-0001-0000-0000-000000000000")
                        },
                        new
                        {
                            RoleId = new Guid("dfb4b5b2-4461-44a6-bcc5-6a2ea5a86f55"),
                            PermissionId = new Guid("00000002-0005-0000-0000-000000000000")
                        },
                        new
                        {
                            RoleId = new Guid("dfb4b5b2-4461-44a6-bcc5-6a2ea5a86f55"),
                            PermissionId = new Guid("00000003-0001-0000-0000-000000000000")
                        },
                        new
                        {
                            RoleId = new Guid("2ba5ccdf-6f97-4e5d-9abe-c2dcd4c66355"),
                            PermissionId = new Guid("00000003-0001-0000-0000-000000000000")
                        },
                        new
                        {
                            RoleId = new Guid("dfb4b5b2-4461-44a6-bcc5-6a2ea5a86f55"),
                            PermissionId = new Guid("00000003-0005-0000-0000-000000000000")
                        },
                        new
                        {
                            RoleId = new Guid("dfb4b5b2-4461-44a6-bcc5-6a2ea5a86f55"),
                            PermissionId = new Guid("00000004-0001-0000-0000-000000000000")
                        },
                        new
                        {
                            RoleId = new Guid("2ba5ccdf-6f97-4e5d-9abe-c2dcd4c66355"),
                            PermissionId = new Guid("00000004-0001-0000-0000-000000000000")
                        },
                        new
                        {
                            RoleId = new Guid("dfb4b5b2-4461-44a6-bcc5-6a2ea5a86f55"),
                            PermissionId = new Guid("00000004-0005-0000-0000-000000000000")
                        },
                        new
                        {
                            RoleId = new Guid("dfb4b5b2-4461-44a6-bcc5-6a2ea5a86f55"),
                            PermissionId = new Guid("00000005-0001-0000-0000-000000000000")
                        },
                        new
                        {
                            RoleId = new Guid("2ba5ccdf-6f97-4e5d-9abe-c2dcd4c66355"),
                            PermissionId = new Guid("00000005-0001-0000-0000-000000000000")
                        },
                        new
                        {
                            RoleId = new Guid("dfb4b5b2-4461-44a6-bcc5-6a2ea5a86f55"),
                            PermissionId = new Guid("00000005-0005-0000-0000-000000000000")
                        },
                        new
                        {
                            RoleId = new Guid("dfb4b5b2-4461-44a6-bcc5-6a2ea5a86f55"),
                            PermissionId = new Guid("00000006-0001-0000-0000-000000000000")
                        },
                        new
                        {
                            RoleId = new Guid("2ba5ccdf-6f97-4e5d-9abe-c2dcd4c66355"),
                            PermissionId = new Guid("00000006-0001-0000-0000-000000000000")
                        },
                        new
                        {
                            RoleId = new Guid("dfb4b5b2-4461-44a6-bcc5-6a2ea5a86f55"),
                            PermissionId = new Guid("00000006-0005-0000-0000-000000000000")
                        },
                        new
                        {
                            RoleId = new Guid("dfb4b5b2-4461-44a6-bcc5-6a2ea5a86f55"),
                            PermissionId = new Guid("00000007-0001-0000-0000-000000000000")
                        },
                        new
                        {
                            RoleId = new Guid("2ba5ccdf-6f97-4e5d-9abe-c2dcd4c66355"),
                            PermissionId = new Guid("00000007-0001-0000-0000-000000000000")
                        },
                        new
                        {
                            RoleId = new Guid("dfb4b5b2-4461-44a6-bcc5-6a2ea5a86f55"),
                            PermissionId = new Guid("00000007-0005-0000-0000-000000000000")
                        },
                        new
                        {
                            RoleId = new Guid("dfb4b5b2-4461-44a6-bcc5-6a2ea5a86f55"),
                            PermissionId = new Guid("00000008-0001-0000-0000-000000000000")
                        },
                        new
                        {
                            RoleId = new Guid("2ba5ccdf-6f97-4e5d-9abe-c2dcd4c66355"),
                            PermissionId = new Guid("00000008-0001-0000-0000-000000000000")
                        },
                        new
                        {
                            RoleId = new Guid("dfb4b5b2-4461-44a6-bcc5-6a2ea5a86f55"),
                            PermissionId = new Guid("00000008-0005-0000-0000-000000000000")
                        },
                        new
                        {
                            RoleId = new Guid("dfb4b5b2-4461-44a6-bcc5-6a2ea5a86f55"),
                            PermissionId = new Guid("00000009-0001-0000-0000-000000000000")
                        },
                        new
                        {
                            RoleId = new Guid("2ba5ccdf-6f97-4e5d-9abe-c2dcd4c66355"),
                            PermissionId = new Guid("00000009-0001-0000-0000-000000000000")
                        },
                        new
                        {
                            RoleId = new Guid("dfb4b5b2-4461-44a6-bcc5-6a2ea5a86f55"),
                            PermissionId = new Guid("00000009-0005-0000-0000-000000000000")
                        },
                        new
                        {
                            RoleId = new Guid("dfb4b5b2-4461-44a6-bcc5-6a2ea5a86f55"),
                            PermissionId = new Guid("0000000a-0001-0000-0000-000000000000")
                        },
                        new
                        {
                            RoleId = new Guid("2ba5ccdf-6f97-4e5d-9abe-c2dcd4c66355"),
                            PermissionId = new Guid("0000000a-0001-0000-0000-000000000000")
                        },
                        new
                        {
                            RoleId = new Guid("dfb4b5b2-4461-44a6-bcc5-6a2ea5a86f55"),
                            PermissionId = new Guid("0000000a-0005-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("ICTMasterSuite.Domain.Entities.SystemSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.HasKey("Id");

                    b.HasIndex("Category", "Key")
                        .IsUnique();

                    b.ToTable("SystemSettings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e67a95c8-fc91-47a4-a358-f8ee7dbb7b3b"),
                            Category = "Finder",
                            CreatedAt = new DateTime(2026, 4, 8, 20, 47, 58, 526, DateTimeKind.Utc).AddTicks(8241),
                            Key = "Directories",
                            Value = ""
                        },
                        new
                        {
                            Id = new Guid("a7ec39fe-48e4-4785-b32b-9a264f71af05"),
                            Category = "Updater",
                            CreatedAt = new DateTime(2026, 4, 8, 20, 47, 58, 526, DateTimeKind.Utc).AddTicks(8242),
                            Key = "Endpoint",
                            Value = ""
                        },
                        new
                        {
                            Id = new Guid("a0cf593a-e9a4-4c54-9e59-f9cd65c50370"),
                            Category = "Updater",
                            CreatedAt = new DateTime(2026, 4, 8, 20, 47, 58, 526, DateTimeKind.Utc).AddTicks(8243),
                            Key = "AutoCheck",
                            Value = "True"
                        },
                        new
                        {
                            Id = new Guid("862954d8-ee99-4006-be15-6dce18609376"),
                            Category = "UI",
                            CreatedAt = new DateTime(2026, 4, 8, 20, 47, 58, 526, DateTimeKind.Utc).AddTicks(8244),
                            Key = "Theme",
                            Value = "Dark"
                        },
                        new
                        {
                            Id = new Guid("5a73b376-4e9b-4f79-99e6-2cf1d37d8a8b"),
                            Category = "UI",
                            CreatedAt = new DateTime(2026, 4, 8, 20, 47, 58, 526, DateTimeKind.Utc).AddTicks(8245),
                            Key = "AutoOpenLastModule",
                            Value = "True"
                        });
                });

            modelBuilder.Entity("ICTMasterSuite.Domain.Entities.TechnicalAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnalysisText")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorCode")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("ErrorDescription")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("LogType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("Result")
                        .HasColumnType("int");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("TechnicianName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SerialNumber");

                    b.ToTable("TechnicalAnalyses", (string)null);
                });

            modelBuilder.Entity("ICTMasterSuite.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b8df2f8a-10af-4a6b-9b95-c485e43a1a14"),
                            CreatedAt = new DateTime(2026, 4, 8, 20, 47, 58, 536, DateTimeKind.Utc).AddTicks(939),
                            Email = "admin@ict.local",
                            FullName = "Administrador do Sistema",
                            IsActive = true,
                            MustChangePassword = true,
                            PasswordHash = "PBKDF2:bCdgbbfRTcWr6KU/d+yRag==:LHMeoym1w0msk94Xse4zEoXsL3nTRD0VgT40h+TOdw8=",
                            RoleId = new Guid("dfb4b5b2-4461-44a6-bcc5-6a2ea5a86f55"),
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("ICTMasterSuite.Domain.Entities.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SessionToken")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserSessions", (string)null);
                });

            modelBuilder.Entity("ICTMasterSuite.Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("ICTMasterSuite.Domain.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ICTMasterSuite.Domain.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ICTMasterSuite.Domain.Entities.User", b =>
                {
                    b.HasOne("ICTMasterSuite.Domain.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ICTMasterSuite.Domain.Entities.UserSession", b =>
                {
                    b.HasOne("ICTMasterSuite.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ICTMasterSuite.Domain.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("ICTMasterSuite.Domain.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
